services:
  - type: web
    name: ai-writing-assistant-backend
    runtime: python
    pythonVersion: 3.11.9
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ANTHROPIC_API_KEY
        sync: false
